apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: blink
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"