apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: blink
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8084"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_DATA_MONGODB_HOST: "mongodb"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "blink_orders"
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: "admin"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"