apiVersion: v1
kind: Service
metadata: 
  name: discovery-server
  namespace: blink
  labels:
    app: discovery-server
spec:
  type:  ClusterIP
  ports: 
  - port: 8761
    targetPort: 8761
  selector:
    app: discovery-server