server:
  port: 8084

spring:
  application: 
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/blink_orders
  kafka:
    bootstrap-servers:  localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: 
            orderEvent: com.blink.order.event.OrderEvent

# Kafka Topics
kafka:
  topic:
    order-created: order-created
    order-updated: order-updated
    order-cancelled: order-cancelled

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.blink.order: DEBUG
    org.apache.kafka: WARN