apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: blink
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8083"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"